<template>
  <div>
    <h1>Terms of Service</h1>
    <p>The following document reviews how 4NTENT will strive to maintain a relationship that is positive to our users. We will review expectations, considerations, and rules that we will be following. Please take time to write down questions that you may have as you read the terms of service. After agreeing to this form you agree to abide by the contents within.</p>
    <p>Thank you for visiting 4NTENT (“We”, “Us”, “Company”, “4NTENT”). These Terms of Use, together with the Privacy Policy, Acceptable Use Policy and any other documents they expressly incorporate, set forth the terms and conditions upon which you may access and use the health coaching services, mobile application and therapy or other related services provided or operated by 4NTENT (collectively, the “Services”), including but not limited to any content and functionality offered through the Services. (“Terms of Use” or “Agreement”)</p>
    <p>PLEASE READ THE TERMS OF USE CAREFULLY BEFORE YOU START TO USE THE SERVICES. THESE TERMS OF USE SET FORTH YOUR RIGHTS AND RESPONSIBILITIES CONCERNING THE SERVICES. THESE TERMS OF USE ALSO; (I) CONTAIN PROVISIONS THAT GOVERN HOW CLAIMS ARE RESOLVED, AND (II) AN AGREEMENT TO ARBITRATE, WHICH WILL, WITH LIMITED EXCEPTION, REQUIRE YOU TO SUBMIT CLAIMS YOU HAVE AGAINST US OR OUR AGENTS TO BINDING AND FINAL ARBITRATION.</p>
    <p>IN ORDER TO USE THE SERVICES, YOU MUST BE AT LEAST 13 YEARS OF AGE AND LOCATED IN THE UNITED STATES. BY USING THE SERVICES, YOU (or, if you are younger than the applicable age of majority, your parent/legal guardian) REPRESENT YOU; (I) ARE AT LEAST 13 YEARS OF AGE, AND (II) ARE LOCATED IN THE UNITED STATES. FURTHER, YOU ACCEPT AND AGREE TO BE BOUND AND ABIDE BY THESE TERMS OF USE. IF YOU ARE NOT 13 YEARS OLD, OR IF YOU ARE LOCATED OUTSIDE OF THE UNITED STATES (IRRESPECTIVE OF YOUR AGE), YOU MUST NOT ACCESS OR USE THE SERVICES. If you are 13 or older, but under the age of 18 or other age of majority in your state of residence (in other words, you are considered a minor), your parent or legal guardian must agree to these Terms of Use on your behalf and you may only access and use the Services with permission from your parent or legal guardian.</p>
    <p>IF YOU ARE A PARENT OR GUARDIAN ACCEPTING THESE TERMS ON BEHALF OF A MINOR YOU ALSO REPRESENT AND WARRANT THAT YOU HAVE READ AND AGREE TO THESE TERMS ON BEHALF OF THE MINOR AND ON YOUR OWN BEHALF. AS A PARENT OR GUARDIAN OF A MINOR USING THE SERVICES YOU ALSO ACKNOWLEDGE THAT YOUR ACCESS AND USE OF THE SERVICES ARE SUBJECT TO THIS AGREEMENT.</p>
    <p>WE RESERVE THE RIGHT TO CHANGE, ADD OR REMOVE PORTIONS OF THESE TERMS OF USE, THE PRIVACY POLICY, AND ANY DOCUMENTS INCORPORATED HEREIN AT ANY TIME AND AT OUR SOLE DISCRETION. YOUR CONTINUED USE OF THE SERVICES FOLLOWING THE POSTING OF ANY CHANGES MEANS THAT YOU ACCEPT AND AGREE TO SUCH CHANGES. IT IS YOUR RESPONSIBILITY TO CHECK THESE TERMS OF USE PERIODICALLY FOR CHANGES.</p>
    <br>
    Definitions.
    <p>“Acceptable Use Policy” means the Acceptable Use Policy attached hereto.</p>
    <p>“Authorized User(s)”, “You”, “Your” means an individual who enters into this Agreement with 4NTENT.</p>
    <p>“Confidential Information” means information disclosed by a party (“Disclosing Party”) to the other party (“Receiving Party”), whether orally or in writing, that is designated as confidential or that reasonably should be understood to be confidential given the nature of the information and the circumstances of disclosure. Confidential Information does not include any information that (i) was known to the Receiving Party prior to its disclosure by the Disclosing Party without breach of any obligation owed to the Disclosing Party; (ii) is or becomes generally known to the public without breach of any obligation owed to the Disclosing Party, (iii) is received from a third party without breach of any obligation owed to the Disclosing Party, or (iv) was independently developed by the Receiving Party without access to the Disclosing Party’s Confidential Information.</p>
    <p>“Content” means information either; (i) created by 4NTENT and made available to Authorized Users through the Services, or (ii) obtained by 4NTENT from publicly available sources or third-party content providers and made available to Authorized Users through the Services.</p>
    <p>“Documentation” means any documentation (online or otherwise) made available or accessible by You describing the Services or any support provided for the Services.</p>
    <p>“Malicious Code” means code, files, scripts, agents or programs intended to do harm, including, for example, viruses, worms, time bombs and Trojan horses.</p>
    <p>“Services” means the 4NTENT services that are ordered by You or provided to You under a free trial or membership and made available online by 4NTENT, including associated offline or mobile components, as described in the Documentation. “Services” exclude Content and Third-Party Technology.</p>
    <p>“Third-Party Technology” means a Web-based, mobile, offline or other software application, technology or functionality that is made available to Authorized Users and interoperates with a Service.</p>
    <p>“4NTENT.com” means 4NTENT and any of its affiliated companies.</p>
    <p>“Your (User) Data” means electronic data and information submitted by or for an Authorized User to the Services, your information will not be shared with 3rd parties without your permission.</p>
    <br>
    Use of the Site.
    <p>4NTENT (“we”, “us”, or “our”) operates the website located at www.4ntent.com and other related websites and mobile applications with links to these Terms of Use (collectively, the “Site”). We offer an online wellness platform for education and empowerment of health and wellness needs. We are not offering or treating in a manor that would be defined as telehealth services. We offer a customized membership model for consumers to build their health and wellness profile via 4NTENT.com.</p>
    <p>4NTENT’s platforms enables our users to report their intentions and engage with health mentors to obtain health mentorship services either in the providers office location or via 4NTENT’s wellness platform. By accessing and using the Site, you agree to be bound by these Terms of Use and all other terms and policies that appear on the Site. If you do not wish to be bound by any of these Terms of Use, you may not use the Site or the Services.</p>
    <p>All of the health mentors who deliver Services through 4NTENT are independent professionals solely responsible for the services and recommendations each provides to you. Each independent provider is bound by their own ethical and professional standards under their certification, licensure, or training. 4NTENT does not practice medicine or any other licensed profession, and does not interfere with the practice of medicine or any other licensed profession of a health mentor, each of whom is responsible for his or her services and compliance with the requirements applicable to his or her profession and license. 4NTENT (“we”, “us”, or “our”) and all associated entities are technology based platforms, not a medical, and/or healthcare platforms. Neither 4NTENT nor any third parties who promote the services or provide you with a link to the service shall be liable for any professional advice you obtain from a health mentor via the services. None of the site content should be considered medical advice or an endorsement, representation or warranty that any particular medication or treatment is safe, appropriate, or effective for you. 4NTENT does not guarantee positive results from use of it’s platform or health mentors. You are at your own risk when engaging with these sites and health mentors. </p>
    <h4 style="text-align: center">Informed Consent</h4>
    Confidentiality.
    <p>When engaging with a 4NTENT Health Mentor or service through 4NTENT’s platforms all discussions that occur within sessions are kept in confidence. Any information, names, relationships, or concerns you share remain confident. Due to the nature of your wellness profile, the health mentors you choose will be in collaboration with one another. You can amend these health mentors at any time or revoke their ability to collaborate. If your safety or someone else’s safety is in question we has health mentors are mandated reporters and we may reach out to your family/friends in emergencies or call 911 if necessary. If you’d like further information shared, please review this process with your health mentor or use the invite a friend feature to connect through out platform. You may designate who you would like information shared with and you may invite whoever you like into your wellness profile.You are responsible for reading and agreeing to 4NTENT’s privacy agreement. Please be aware that if we communicate via email, text, or online, your information may not be protected and you will be running the risk of exposure. There are technological risks that may occur during sessions such as session ending due to poor connection, delay in video/sound, to name a few. You agree to these potential risks and to provide feedback regarding your experience so that 4NTENT can improve the technology used. Hypothetically the system administrator would have access to these past logs or conversations and sites can be hacked.</p>
    <p>If you engage in a family program with 4NTENT health mentors but decide to take advantage of a few individual sessions please know that what you bring up in your individual session will also be included in the families programming. Please do not disclose anything to our health mentors that you would not also want to share with your family. This is 4NTENT’s “no secret” policy. If you engage in teen programs please keep in mind that what a teen shares will not always be shared with parents to build confidence, rapport, and trust with 4NTENT’s team. Required Reporting and ensuring your Safety: All 4NTENT’s health mentors serve as mandated reporters. If we have any reason to believe that you or someone you know may be in danger, in a crisis, or your safety is at risk we have the right to seek out information from your family and friends to ensure your safety. If we feel you are a danger to yourself or someone else we will be contacting your friends, family and the police to ensure safety for all parties involved.</p>
    <p>If there is any reason to believe that abuse or neglect of a child or minor is occurring, most of our health mentors are mandated reporters and are required to report to the child protective services or to local law enforcement (police or sheriff’s department) immediately by phone. A written report must then be sent within 36 hours by fax, or it may be sent by electronic submission, if a secure system has been made available for that purpose. Written reports must be submitted on the California Suspected Child Abuse Report Form 8572. If a minor reports having non-consensual sexual contact our health mentors will review what is legal and appropriate and will take action of reporting to authorities in compliance with California state laws. If you report any form of abuse or inappropriate conduct from another named health care provider or counselor we are required to report this to the provider’s existing board and the California Department of Health.</p>
    <br>
    Your Wellness Profile.
    <p>All of your records within the wellness profile are password protected and set up by you at the beginning of your engagement with 4NTENT. You may always change your password, delete your account, and or ask for support to locate past data. Our account administrator has access to information that is stored so please only share information you are comfortable with in your profile section. We advise our health mentors to only take minimal notes during sessions which disclose the main topics of education who attended, and the plan for following sessions. If you wish to have the health mentor refrain from taking notes please inform us of this request in writing and we will keep this in your record. 4NTENT does not get involved with court related proceedings due to divorce or custody disputes.</p>
    <p>Information contained in your wellness profile is confidential and protected to the best of our ability. Information you enter into your wellness profile is the only information that your chosen health mentors will see in addition to your comments during 1:1 programs or group programs. If you’d like further insights to be shared with an outside medical provider we would ask that a release of information is signed. 4NTENT does not interact or accept insurance so information is not disclosed for payment to 3rd parties. 4NTENT does utilize PayPal as a payment interface so your information may be at risk if PayPal experiences a breech of data.</p>
    <p>Complaints or Lawsuits: if you file a complaint or lawsuit against us, we must provide any requested information or any information relating to the health mentor’s defense of him/herself.</p>
    <br>
    Approach to Our Programs.
    <p>4NTENT provides our users with wellness and empowerment education to allow our users to set intentions while making a difference in the community. 4NTENT’s team is typically made up of mental health professionals, personal trainers, and nutritionists/dietitians. These professionals will be collaborating on your individual wellness profile and across programs to ensure you are getting the support of unique wellness backgrounds. Several wellness models may be used in our approach with our health mentors. Know that you may be asked to engage in specific activities within the programs and you may be asked to complete homework outside of scheduled programs. You are welcome to engage in all of some of our options within your wellness profile. When engaging in any of your programs, you are in the driver’s seat. Please share what you are comfortable with sharing and we may coach you to share additional aspects with other members. All users will be asked to maintain confidentiality of other users when interacting on the site. 4NTENT’s health mentors work as a team and may need to consult with other health mentors regarding your wellness profile.</p>
    <p>Conversations regarding your wellness, goals, and needs will only be disclosed to other 4NTENT health mentors as it pertains to your intentions and will be discussed with you prior to disclosure.</p>
    <h4>Expectations for the user:</h4>
    <h5>Scheduling</h5>
    <p>As the user you are required to RSVP to our programs and schedule with your health mentor. They will guide you to how to best schedule with them.</p>
    <h5>Cancellations</h5>
    <p>Please email or message your health mentor at least 24 hours before your session time. If 4NTENT health mentors do not receive 24 hours notice, we are able to bill for the normal program rate.</p>
    <h4>Missing Session/Group dates</h4>
    <p>If you miss a day or two within the week, we will follow up with you to inquire about rescheduling. If we are unable to reach you it is your responsibility to reschedule or sign up again for a future group/session time.</p>
    <h5>During Programs</h5>
    <p>While in a program, you are only required to disclose what you are comfortable with sharing. If we ask you additional questions you do not wish to answer or explore you may simply refuse. We may decide to switch to a different activity during our programs which would enhance our work. If this occurs we will ask for verbal consent before exploring anything new. We may give additional homework or ask you to engage in activities during our sessions. We highly encourage you to try these activities as they will enhance and speed up your empowerment process. Please feel encouraged to engage.</p>
    <h5>Divorce Decrees</h5>
    <p>4NTENT will ask one parent to be responsible for their child’s/children’s account. Our policy is to have one parent provide payment and we will not enter into any disputes.</p>
    <h5>Contacting Us</h5>
    <p>You may contact 4NTENT via email at empower@4ntent.com or phone at 323-682-0451. If you are calling after hours for an emergency call 911 or the crisis hotline at 888-724-7240. If you attempt contacting our health mentor’s personal email, phone numbers, or social media sites it is our company policy to ignore and delete these requests. Please use the journaling feature within your wellness profile to maintain notes. Please do not write anything in the online journal you wouldn’t be comfortable sharing with your health mentor or group.</p>
    <h4>Fees:</h4>
    <p>a. 4NTENT’s general website is free to utilize as well as our wellness profile quiz. 4NTENT is a membership model where users pick one of three packages or customize their own experience.</p>
    <p>b. Financial Policy: Finances are just one aspect of entering into the relationship with the 4NTENT team. The following describes our financial policy and procedure process. 4NTENT’s health mentors are subject to a separate fee arrangement than our members. Payments to mentors will be done so directly through the 4NTENT’s platform.</p>
    <p>c. Payment: 4NTENT accepts the following forms of payment: Paypal and all major debit/credit cards. Payments will be paid in full at time of purchase. Regarding memberships, fees will be automatically billed (ACH process). All payments received are processed in a secure manner to protect your privacy.</p>
    <p>d. Billing Cycle occurs monthly: 4NTENT will auto debit your your membership on the first of the month to the credit/debit/account number we have on file. If you’d like to adjust your payment settings or membership, you can do so at any time by visiting your profile. </p>
    <p>e. Late payments/delinquent accounts: An account is considered delinquent or late if it is past 30 days from the statement date. 4NTENT reserves the right to charge interest up to the amount of the law for late payments. If the account is 90 days past due it is considered delinquent and can be submitted to a collection agency. Any legal fees incurred during the collection process will also be the responsibility of the person responsible for the account.</p>
    <p>f. Consequences for Non-payment: 4NTENT reserves the right to discontinue the user profile/membership for delinquent user accounts. If this applies to you we will discuss the matter with you and our billing department will offer solutions to get your account back into a healthy state.</p>
    <p>g. Fees. Our membership fees are as follows:
      <p>Passion Membership $99.99/month</p>
      <p>Purpose Membership $199.99/month</p>
      <p>Empower Membership $499.99/month</p>
      <p>*Upgrade options are available per each membership and prices are posted on the website.</p>
    </p>
    <br>
    Concerns or Complaints.
    <p>If you have any concerns or complaints regarding our process or health mentors, we hope you feel comfortable to address these with us. We are open to your feedback and would like to improve the process with every opportunity. If you feel that your concerns will not be recognized or handled appropriately within our team you may report your concerns to:</p>
    <span style="display: block">4NTENT</span>
    <span style="display: block">empower@4ntent.com</span>
    <br>
    AGREEMENT BETWEEN USER AND 4NTENT.
    <p>The 4NTENT website is comprised of various Web pages operated by 4NTENT. 4NTENT website is offered to you conditioned on your acceptance without modification of the terms, conditions, and notices contained herein. Your use of the 4NTENT’s Web Site constitutes your agreement to all such terms, conditions, and notices.</p>
    <br>
    MODIFICATION OF THESE TERMS OF USE.
    <p>4NTENT reserves the right to change the terms. conditions, and notices under which the 4NTENT’s Web Site is offered, including but not limited to the charges associated with the use of the 4NTENT’s Web Site.</p>
    <br>
    LINKS TO THIRD PARTY SITES.
    <p>4NTENT’s Web Site may contain links to other web Sites (“Linked Sites”). The Linked Sites are not under the control of 4NTENT and 4NTENT is not responsible for the contents of any Linked Site, including without limitation any link contained in a Linked Site, or any changes or updates to a Linked Site. 4NTENT is not responsible for webcasting or any other form of transmission received from any Linked Site. 4NTENT is providing these links to you only as a convenience, and the inclusion of any link does not imply endorsement by 4NTENT of the site or any association with its operators.</p>
    <br>
    NO UNLAWFUL OR PROHIBITED USE.
    <p>As a condition of your use of the 4NTENT’s Web Site, you warrant to 4NTENT that you will not use the 4NTENT Web Site for any purpose that is unlawful or prohibited by these terms, conditions, and notices. You may not use the 4NTENT Web Site in any manner which could damage, disable, overburden, or impair the 4NTENT Web Site or interfere with any other party’s use and enjoyment of the 4NTENT Web Site. You may not obtain or attempt to obtain any materials or information through any means not intentionally made available or provided for through the 4NTENT’s Web Sites.</p>
    <br>
    USE OF COMMUNICATION SERVICES.
    <p>The 4NTENT Web Site may contain bulletin board services, chat areas, news groups, forums, communities, personal web pages, calendars, and/or other message or communication facilities designed to enable you to communicate with the public at large or with a group (collectively, “Communication Services”), you agree to use the Communication Services only to post, send and receive messages and material that are proper and related to the particular Communication Service. By way of example, and not as a limitation, you agree that when using a Communication Service, you will not:</p>
    <p>• Defame, abuse, harass, stalk, threaten or otherwise violate the legal rights (such as rights of privacy and publicity) of others.</p>
    <p>• Publish, post, upload, distribute or disseminate any inappropriate, profane, defamatory, infringing, obscene, indecent or unlawful topic, name, material or information.</p>
    <p>• Upload files that contain software or other material protected by intellectual property laws (or by rights of privacy of publicity) unless you own or control the rights thereto or have received all necessary consents.</p>
    <p>• Upload files that contain viruses, corrupted files, or any other similar software or programs that may damage the operation of another’s computer.</p>
    <p>• Advertise or offer to sell or buy any goods or services for any business purpose, unless such Communication Service specifically allows such messages.</p>
    <p>• Conduct or forward surveys, contests, pyramid schemes or chain letters.</p>
    <p>• Download any file posted by another user of a Communication Service that you know, or reasonably should know, cannot be legally distributed in such manner.</p>
    <p>• Falsify or delete any author attributions, legal or other proper notices or proprietary designations or labels of the origin or source of software or other material contained in a file that is uploaded.</p>
    <p>• Restrict or inhibit any other user from using and enjoying the Communication Services.</p>
    <p>• Violate any code of conduct or other guidelines which may be applicable for any particular Communication Service.</p>
    <p>• Harvest or otherwise collect information about others, including e-mail addresses, without their consent.</p>
    <p>• Violate any applicable laws or regulations.</p>
    <br>
    <p>4NTENT has no obligation to monitor the Communication Services. However, 4NTENT reserves the right to review materials posted to a Communication Service and to remove any materials in its sole discretion.</p>
    <br>
    <p>
      4NTENT reserves the right to terminate your access to any or all of the Communication Services at any time without notice for any reason whatsoever.
    </p>
    <br>
    <p>
      4NTENT reserves the right at all times to disclose any information as necessary to satisfy any applicable law, regulation, legal process or governmental request, or to edit, refuse to post or to remove any information or materials, in whole or in part, in 4NTENT’s sole discretion.
    </p>
    <br>
    <p>
      Always use caution when giving out any personally identifying information about yourself or your children in any Communication Service. 4NTENT does not control or endorse the content, messages or information found in any Communication Service and, therefore, 4NTENT specifically disclaims any liability with regard to the Communication Services and any actions resulting from your participation in any Communication Service. Managers and hosts are not authorized 4NTENT spokespersons, and their views do not necessarily reflect those of 4NTENT. Materials uploaded to a Communication Service may be subject to posted limitations on usage, reproduction and/or dissemination. You are responsible for adhering to such limitations if you download the materials.</p>
    <br>
    MATERIALS PROVIDED TO 4NTENT OR POSTED AT ANY 4NTENT WEB SITES.
    <p>4NTENT does not claim ownership of the materials you provide to 4NTENT (including feedback and suggestions) or post, upload, input or submit to any 4NTENT Web Site or its associated services (collectively “Submissions”). However, by posting, uploading, inputting, providing or submitting your Submission you are granting 4NTENT, its affiliated companies and necessary sublicensees permission to use your Submission in connection with the operation of their Internet businesses including, without limitation, the rights to: copy, distribute, transmit, publicly display, publicly perform, reproduce, edit, translate and reformat your Submission; and to publish your name in connection with your Submission. No compensation will be paid with respect to the use of your Submission, as provided herein. 4NTENT is under no obligation to post or use any Submission you may provide and may remove any Submission at any time in 4NTENT’s sole discretion. By posting, uploading, inputting, providing or submitting your Submission you warrant and represent that you own or otherwise control all of the rights to your Submission as described in this section including, without limitation, all the rights necessary for you to provide, post, upload, input or submit the Submissions.
    </p>
    <br>
    <p>
      When you register on the site you are required to create a profile and log in each time you wish to access the site. This includes your name, email, and password. If you are not 18 years of age you must have your parent or guardian consent to use your account. You agree that the account information is accurate, up to date, and if any changes occur you will notify 4NTENT of these changes. You may not transfer, share, or create sub accounts with your account information with anyone. You are responsible for maintaining the confidentiality of your account password and all activities that occur under your account. 4NTENT reserves the right to take any and all action, as it deems necessary or reasonable, regarding the security of the site and your account. 4NTENT shall not be held liable under any circumstances for any liabilities or damages resulting from the use or interaction with the site or your release of account information to a third party. Using another person’s account is prohibited.
    </p>
    <br>
    LIABILITY DISCLAIMER.
    <p>
      THE INFORMATION, SOFTWARE, PRODUCTS, AND SERVICES INCLUDED IN OR AVAILABLE THROUGH THE 4NTENT WEB SITES MAY INCLUDE INACCURACIES OR TYPOGRAPHICAL ERRORS. CHANGES ARE PERIODICALLY ADDED TO THE INFORMATION HEREIN. 4NTENT RUN AND/OR ITS SUPPLIERS MAY MAKE IMPROVEMENTS AND/OR CHANGES IN THE 4NTENT WEB SITE AT ANY TIME. ADVICE RECEIVED VIA THE 4NTENT WEB SITE SHOULD NOT BE RELIED UPON FOR PERSONAL, MEDICAL, LEGAL OR FINANCIAL DECISIONS AND YOU SHOULD CONSULT AN APPROPRIATE PROFESSIONAL FOR SPECIFIC ADVICE TAILORED TO YOUR SITUATION. 4NTENT AND/OR ITS SUPPLIERS MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY, RELIABILITY, AVAILABILITY, TIMELINESS, AND ACCURACY OF THE INFORMATION, SOFTWARE, PRODUCTS, SERVICES AND RELATED GRAPHICS CONTAINED ON THE 4NTENT WEB SITE FOR ANY PURPOSE. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, ALL SUCH INFORMATION, SOFTWARE, PRODUCTS, SERVICES AND RELATED GRAPHICS ARE PROVIDED “AS IS” WITHOUT WARRANTY OR CONDITION OF ANY KIND. 4NTENT AND/OR ITS SUPPLIERS HEREBY DISCLAIM ALL WARRANTIES AND CONDITIONS WITH REGARD TO THIS INFORMATION, SOFTWARE, PRODUCTS, SERVICES AND RELATED GRAPHICS, INCLUDING ALL IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT.TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL 4NTENT AND/OR ITS SUPPLIERS BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF USE, DATA OR PROFITS, ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE USE OR PERFORMANCE OF THE 4NTENT WEB SITE, WITH THE DELAY OR INABILITY TO USE THE 4NTENT WEB SITE OR RELATED SERVICES, THE PROVISION OF OR FAILURE TO PROVIDE SERVICES, OR FOR ANY INFORMATION, SOFTWARE, PRODUCTS, SERVICES AND RELATED GRAPHICS OBTAINED THROUGH THE 4NTENT WEB SITE, OR OTHERWISE ARISING OUT OF THE USE OF THE 4NTENT WEB SITE, WHETHER BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY OR OTHERWISE, EVEN IF 4NTENT OR ANY OF ITS SUPPLIERS HAS BEEN ADVISED OF THE POSSIBILITY OF DAMAGES. BECAUSE SOME STATES/JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, THE ABOVE LIMITATION MAY NOT APPLY TO YOU. IF YOU ARE DISSATISFIED WITH ANY PORTION OF THE 4NTENT WEB SITE, OR WITH ANY OF THESE TERMS OF USE, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING THE 4NTENT WEB SITE.</p>
    <br>
    SERVICE CONTACT.
    <p>empower@4ntent.com</p>
    <br>
    TERMINATION/ACCESS RESTRICTION.
    <p>4NTENT reserves the right, in its sole discretion, to terminate your access to the 4NTENT Web Sites and the related services or any portion thereof at any time, without notice. GENERAL: To the maximum extent permitted by law, this agreement is governed by the laws of the State of California, U.S.A. and you hereby consent to the exclusive jurisdiction and venue of courts in San Diego County, California, U.S.A. in all disputes arising out of or relating to the use of the 4NTENT Web Site. Use of the 4NTENT Web Site is unauthorized in any jurisdiction that does not give effect to all provisions of these terms and conditions, including without limitation this paragraph. You agree that no joint venture, partnership, employment, or agency relationship exists between you and 4NTENT as a result of this agreement or use of the 4NTENT Web Site. 4NTENT’s performance of this agreement is subject to existing laws and legal process, and nothing contained in this agreement is in derogation of 4NTENT’s right to comply with governmental, court and law enforcement requests or requirements relating to your use of the 4NTENT Web Site or information provided to or gathered by 4NTENT with respect to such use. If any part of this agreement is determined to be invalid or unenforceable pursuant to applicable law including, but not limited to, the warranty disclaimers and liability limitations set forth above, then the invalid or unenforceable provision will be deemed superseded by a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of the agreement shall continue in effect. Unless otherwise specified herein, this agreement constitutes the entire agreement between the user and 4NTENT with respect to the 4NTENT Web Site and it supersedes all prior or contemporaneous communications and proposals, whether electronic, oral or written, between the user and 4NTENT with respect to the 4NTENT Web Site. A printed version of this agreement and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to this agreement to the same extent an d subject to the same conditions as other business documents and records originally generated and maintained in printed form. It is the express wish to the parties that this agreement and all related documents be drawn up in English.</p>
    <br>
    COPYRIGHT AND TRADEMARK NOTICES.
    <p>All contents of the 4NTENT Web Site are: © 2019 4NTENT. All rights reserved and/or its suppliers. All rights reserved.</p>
    <br>
    TRADEMARKS.
    <p>The names of actual companies and products mentioned herein may be the trademarks of their respective owners. The example companies, organizations, products, people and events depicted herein are fictitious. No association with any real company, organization, product, person, or event is intended or should be inferred. Any rights not expressly granted herein are reserved.</p>
    <br>
    NOTICES AND PROCEDURE FOR MAKING CLAIMS OF COPYRIGHT INFRINGEMENT.
    <p>Pursuant to Title 17, United States Code, Section 512(c)(2), notifications of claimed copyright infringement under United States copyright law should be sent to Service Provider’s Designated Agent. ALL INQUIRIES NOT RELEVANT TO THE FOLLOWING PROCEDURE WILL RECEIVE NO RESPONSE. See Notice and Procedure for Making Claims of Copyright Infringement.</p>
    <br>
    USER CONSENT.
    <p>I have read and understand the above responsibilities that apply to the 4NTENT technology platforms. I agree to maintain the terms and discuss questions as they arise. I agree to the financial policy and will be held accountable for accrued fees with 4NTENT’s platforms. If I choose I may terminate this agreement at any time without consequence. I agree to begin my empowerment journey with 4NTENT.</p>
  </div>
</template>
<script>
export default {
  name: 'terms-and-conditions',
  components: {},
  data() {
    return {}
  }
}

</script>
